import mongoose from "mongoose";
const Schema = mongoose.Schema;

export const VehicleSchema = new Schema({
	id: String,
	vin: String,
	vid_stock: String,
	date_min: String,
	date_max: String,
	days_total: Number,
	listing_stock: String,
	listing_price: String,
	listing_type: String,
	listing_mileage: String,
	vehicle_year: String,
	vehicle_make: String,
	vehicle_model: String,
	vehicle_trim: String,
	vehicle_color_exterior: String,
	vehicle_color_interior: String,
	listing_vdp_url: String,
	vehicle_dealer_attribution_score: String,
	vehicle_dealer_attribution_level: String,
	listing_description: String,
	listing_features: String,
	vehicle_title: String,
	vehicle_type: String,
	vehicle_engine: String,
	vehicle_transmission: String,
	vehicle_transmission_type: String,
	vehicle_drivetrain: String,
	vehicle_doors: String,
	vehicle_fuel_type: String,
	vehicle_fuel_efficiency: String,
	vehicle_fuel_efficiency_highway: String,
	vehicle_fuel_efficiency_city: String,
	vehicle_trim_id: String,
	va_seller_id: String,
	va_seller_name: String,
	va_seller_address: String,
	va_seller_city: String,
	va_seller_county: String,
	va_seller_state: String,
	va_seller_zip: String,
	va_seller_country: String,
	va_seller_websites: String,
	va_seller_domains: String,
	va_seller_phones: String,
	va_seller_type: String,
	va_seller_makes: String,
	va_seller_latitude: String,
	va_seller_longitude: String,
	imgset_urls: String,
	photo_urls: String,
	certified_preowned_flag: String,
	vehicle_engine_cylinders: Number,
	vehicle_engine_size: String,
	vehicle_style: String,
	vehicle_subtitle: String,
	vehicle_transmission_speed: String,
	vehicle_truck_bed_style: String,
	vehicle_truck_cab_style: String,
	location: {
		type: String,
		coordinates: [Number]
	}
});
